<a href="https://colab.research.google.com/github/lhmisho/Amazon-web-crawling-using-scrapy/blob/master/Copy_of_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Datatype && Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [3]:
a2 = np.array([[1,3,3.2], [4.4, 5.6, 6]])

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [ ]:
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [4]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1.shape

(3,)

In [ ]:
a2.shape

(2, 3)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
import pandas as pd
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [ ]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  3.2
1  4.4  5.6  6.0

## Reshaping & Transposing

In [5]:
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a2.reshape(2,3,1)

array([[[1. ],
        [3. ],
        [3.2]],

       [[4.4],
        [5.6],
        [6. ]]])

In [10]:
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [12]:
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

array([[[1. ],
        [3. ],
        [3.2]],

       [[4.4],
        [5.6],
        [6. ]]])

In [13]:
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [ 12. ,  15. ,  18. ],
        [ 22.4,  25.6,  28.8]],

       [[ 44. ,  48.4,  52.8],
        [ 72.8,  78.4,  84. ],
        [ 96. , 102. , 108. ]]])

In [14]:
# Transpose = swap the axis
a2.T

array([[1. , 4.4],
       [3. , 5.6],
       [3.2, 6. ]])

In [16]:
a2.shape

(2, 3)

## Dot Product

In [19]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [20]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [21]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [22]:
mat3 = np.dot(mat1, mat2.T)

In [23]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [24]:
mat3.shape

(5, 5)