<a href="https://colab.research.google.com/github/lhmisho/Amazon-web-crawling-using-scrapy/blob/master/numpy-practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Datatype && Attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,3,3.2], [4.4, 5.6, 6]])

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [8]:
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
import pandas as pd
a2

array([[1. , 3. , 3.2],
       [4.4, 5.6, 6. ]])

In [18]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  3.2
1  4.4  5.6  6.0